#pragma once

#define VENDOR_ID       0xFEED
#define PRODUCT_ID      0x7131
#define DEVICE_VER      0x0001
#define MANUFACTURER    "Arturas Medvedevas"
#define PRODUCT         "DactylTrackball"

#define MATRIX_COL_PINS { GP6, GP7, GP8, GP9, GP10, GP11 }
#define MATRIX_COL_PINS_RIGHT { GP11, GP10, GP9, GP8, GP7, GP6 }

#define MATRIX_ROW_PINS { GP12, GP13, GP14, GP15, GP20, GP21 } 
#define MATRIX_ROW_PINS_RIGHT { GP12, GP13, GP14, GP15, GP20 }

#define MATRIX_ROWS 12
#define MATRIX_COLS 6

// Serial & Split
#define SERIAL_USART_TX_PIN GP1
#define SPLIT_LAYER_STATE_STATEFUL
#define SPLIT_MODS_ENABLE
#define SPLIT_COMMON_ENABLE
#define SPLIT_USB_DETECT
#define MASTER_LEFT

// Trackball & OLED Settings (Keep these)
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP16
#define PMW33XX_CS_PIN GP17
#define PMW33XX_CPI 800 
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_RIGHT 
#define POINTING_DEVICE_INVERT_Y 
#define SPLIT_POINTING_ENABLE

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3
#define OLED_DISPLAY_128X32
#define OLED_ROTATION 0

#define POINTING_DEVICE_CPI_LIST { 400, 800, 1200, 1600 }
//#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_SNIPING_ENABLE
#define POINTING_DEVICE_SNIPING_CPI 200